apiVersion: v2
name: canvas-oda
description: A Helm of helm to orchestrate the ODA instalation

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"
dependencies:
  - name: cert-manager-init
    version: "1.0.0"
    repository: 'file://../cert-manager-init'
  - name: canvas-namespaces
    version: "1.1.0"
    repository: 'file://../canvas-namespaces'
    condition: canvas-namespaces.enabled
  - name: oda-crds
    version: "1.0.0"
    repository: 'file://../oda-crds'
    condition: oda-crds.enabled
  - name: keycloak
    version: "13.0.2"
    repository: 'https://charts.bitnami.com/bitnami'
    condition: keycloak.enabled
  - name: controller
    version: "1.0.1"
    repository: 'file://../controller'
  - name: oda-webhook
    version: "1.0.0"
    repository: 'file://../oda-webhook'

